Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket Name where to sync your Obsidian vault
  KendraIndexName:
    Type: String
    Description: Name of the Kendra index
  KnowledgeBaseName:
    Type: String
    Description: Name of the knowledge base
Resources:
  S3SyncBucket63F6745B:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName:
        Ref: BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - DELETE
            AllowedOrigins:
              - app://obsidian.md
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: KbStackStack/S3SyncBucket/Resource
  KendraIndexRoleDB7DF3D0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/CloudWatchLogsFullAccess
    Metadata:
      aws:cdk:path: KbStackStack/KendraIndexRole/Resource
  KendraGenAIIndex:
    Type: AWS::Kendra::Index
    Properties:
      Edition: GEN_AI_ENTERPRISE_EDITION
      Name:
        Ref: KendraIndexName
      RoleArn:
        Fn::GetAtt:
          - KendraIndexRoleDB7DF3D0
          - Arn
      UserContextPolicy: ATTRIBUTE_FILTER
    Metadata:
      aws:cdk:path: KbStackStack/KendraGenAIIndex
  S3DataSourceRole8ABEC96D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: KbStackStack/S3DataSourceRole/Resource
  S3DataSourceRoleDefaultPolicy443E6430:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - S3SyncBucket63F6745B
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - S3SyncBucket63F6745B
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: S3DataSourceRoleDefaultPolicy443E6430
      Roles:
        - Ref: S3DataSourceRole8ABEC96D
    Metadata:
      aws:cdk:path: KbStackStack/S3DataSourceRole/DefaultPolicy/Resource
  AllowS3DataSourceToAccessIndexACF3CF5A:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - kendra:BatchDeleteDocument
              - kendra:BatchPutDocument
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - KendraGenAIIndex
                - Arn
        Version: "2012-10-17"
      PolicyName: AllowS3DataSourceToAccessIndexACF3CF5A
      Roles:
        - Ref: S3DataSourceRole8ABEC96D
    Metadata:
      aws:cdk:path: KbStackStack/AllowS3DataSourceToAccessIndex/Resource
  S3DataSource:
    Type: AWS::Kendra::DataSource
    Properties:
      DataSourceConfiguration:
        S3Configuration:
          BucketName:
            Ref: S3SyncBucket63F6745B
      IndexId:
        Fn::GetAtt:
          - KendraGenAIIndex
          - Id
      Name: S3DataSource
      RoleArn:
        Fn::GetAtt:
          - S3DataSourceRole8ABEC96D
          - Arn
      Type: S3
    DependsOn:
      - AllowS3DataSourceToAccessIndexACF3CF5A
      - S3DataSourceRoleDefaultPolicy443E6430
    Metadata:
      aws:cdk:path: KbStackStack/S3DataSource
  KnowledgeBaseRoleA2B317B9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
              ArnLike:
                aws:SourceArn:
                  Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":bedrock:"
                      - Ref: AWS::Region
                      - ":"
                      - Ref: AWS::AccountId
                      - :knowledge-base/*
            Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: KbStackStack/KnowledgeBaseRole/Resource
  AllowAccessingKendra2F5CFC4E:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - kendra:DescribeIndex
              - kendra:Retrieve
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - KendraGenAIIndex
                - Arn
        Version: "2012-10-17"
      PolicyName: AllowAccessingKendra2F5CFC4E
      Roles:
        - Ref: KnowledgeBaseRoleA2B317B9
    Metadata:
      aws:cdk:path: KbStackStack/AllowAccessingKendra/Resource
  KnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Description: Knowledge Base for Obsidian data vault
      KnowledgeBaseConfiguration:
        KendraKnowledgeBaseConfiguration:
          KendraIndexArn:
            Fn::GetAtt:
              - KendraGenAIIndex
              - Arn
        Type: KENDRA
      Name:
        Ref: KnowledgeBaseName
      RoleArn:
        Fn::GetAtt:
          - KnowledgeBaseRoleA2B317B9
          - Arn
    DependsOn:
      - AllowAccessingKendra2F5CFC4E
    Metadata:
      aws:cdk:path: KbStackStack/KnowledgeBase
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/y2MQQ6CMBREz8K+fAU2ukU3xg2BA5hP+zWlpU3aIpqGu1vA1Uzem0wJxekMRYazz7lQuZY9xC4gV+zyNA06HCmQY8k/oq8g1hNXFFa5t4VJHCG2VtMKt2yslvy7HWxtYYqMcAgxoZsR9FndFQN2dnKcFtaTcJYrSPhu7KxJvKhGn0xL/r8xVhAM/vAuKygKOGaDlzJ3kwlyJGj3/AHinA7K0AAAAA==
    Metadata:
      aws:cdk:path: KbStackStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-3
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-3
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-4
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
      - Fn::Equals:
          - Ref: AWS::Region
          - us-west-2
